import type { Metadata } from "next";
import "./style/main.scss";
import Script from "next/script";
import { ReduxProvider } from "@/redux/provider";
import '../app/style/main.scss';

export const metadata: Metadata = {
  title: "Art UI App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        src="/bootstrap.min.js"
        strategy="afterInteractive"
      />
      <body>
        <ReduxProvider>
            {children}
        </ReduxProvider>

      </body>
    </html>
  );
}
